language: c
script: ./test.sh
before_install:
  - sudo cat /etc/lsb-release

  # update sources
  - sudo apt-get --quiet=2 --download-only update

  # install go
  - sudo wget https://storage.googleapis.com/golang/go1.7.linux-amd64.tar.gz
  - sudo tar -xzf go1.7.linux-amd64.tar.gz -C /usr/local
  - export GOPATH=$PWD
  - export PATH=$GOPATH/bin:$PATH

  # install node
  - node --version || true
  - nodejs --version || true
  - which -a node
  - which -a nodejs
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -
  - sudo apt-get --yes install nodejs
  - node --version || true
  - nodejs --version || true
  - which -a node
  - which -a nodejs
  - export PATH=$PWD/app/node_modules/.bin:$PATH

  # pull node modules
  - pushd app; npm install; popd

  # install 0mq
  - sudo apt-get --yes install python-software-properties
  - sudo add-apt-repository --yes ppa:chris-lea/zeromq
  - sudo apt-get update
  - sudo apt-get install zeromq
  - sudo apt-get --yes install build-essential pkg-config
  - export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
