language: go
go:
  - 1.7
env:
  - PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
script: ./test.sh
go_import_path: github.com/jasonkeene/anubot
before_install:
  - sudo apt-get --quiet=2 --download-only update
  - sudo apt-get --assume-yes install git nodejs npm
  - sudo ln -s /usr/bin/node{js,}
  - sudo apt-get --assume-yes install build-essential pkg-config libzmq3-dev
  - git submodule update --init --recursive
  - pushd app; npm install; popd
